// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rank_matrix_cpp
NumericMatrix rank_matrix_cpp(NumericMatrix mat, bool descending, bool use_abs);
RcppExport SEXP _influential_rank_matrix_cpp(SEXP matSEXP, SEXP descendingSEXP, SEXP use_absSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type descending(descendingSEXP);
    Rcpp::traits::input_parameter< bool >::type use_abs(use_absSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_matrix_cpp(mat, descending, use_abs));
    return rcpp_result_gen;
END_RCPP
}
// flatten_cor_matrix_cpp
List flatten_cor_matrix_cpp(NumericMatrix cormat, Nullable<NumericMatrix> mrmat, Nullable<NumericMatrix> pmat, Nullable<NumericMatrix> padjmat, CharacterVector row_names);
RcppExport SEXP _influential_flatten_cor_matrix_cpp(SEXP cormatSEXP, SEXP mrmatSEXP, SEXP pmatSEXP, SEXP padjmatSEXP, SEXP row_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cormat(cormatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type mrmat(mrmatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type padjmat(padjmatSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type row_names(row_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(flatten_cor_matrix_cpp(cormat, mrmat, pmat, padjmat, row_names));
    return rcpp_result_gen;
END_RCPP
}
// flatten_rect_cor_matrix_cpp
List flatten_rect_cor_matrix_cpp(NumericMatrix cormat, Nullable<NumericMatrix> mrmat, Nullable<NumericMatrix> pmat, Nullable<NumericMatrix> padjmat, CharacterVector row_names, CharacterVector col_names);
RcppExport SEXP _influential_flatten_rect_cor_matrix_cpp(SEXP cormatSEXP, SEXP mrmatSEXP, SEXP pmatSEXP, SEXP padjmatSEXP, SEXP row_namesSEXP, SEXP col_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cormat(cormatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type mrmat(mrmatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type padjmat(padjmatSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type row_names(row_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col_names(col_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(flatten_rect_cor_matrix_cpp(cormat, mrmat, pmat, padjmat, row_names, col_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_influential_rank_matrix_cpp", (DL_FUNC) &_influential_rank_matrix_cpp, 3},
    {"_influential_flatten_cor_matrix_cpp", (DL_FUNC) &_influential_flatten_cor_matrix_cpp, 5},
    {"_influential_flatten_rect_cor_matrix_cpp", (DL_FUNC) &_influential_flatten_rect_cor_matrix_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_influential(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
