# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rank_matrix_cpp <- function(mat, descending = TRUE, use_abs = FALSE) {
    .Call(`_influential_rank_matrix_cpp`, mat, descending, use_abs)
}

flatten_cor_matrix_cpp <- function(cormat, mrmat = NULL, pmat = NULL, padjmat = NULL, row_names = as.character( c())) {
    .Call(`_influential_flatten_cor_matrix_cpp`, cormat, mrmat, pmat, padjmat, row_names)
}

flatten_rect_cor_matrix_cpp <- function(cormat, mrmat = NULL, pmat = NULL, padjmat = NULL, row_names = as.character( c()), col_names = as.character( c())) {
    .Call(`_influential_flatten_rect_cor_matrix_cpp`, cormat, mrmat, pmat, padjmat, row_names, col_names)
}

